<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE details
[
<!ELEMENT details (address, phone, full-Name, age)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT full-Name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
]>
<details>
    <address>23 George Amewhule Street</address>
    <phone>070133398499</phone>
    <full-Name>Dennis Nelson Inueibia</full-Name>
    <age>21</age>
</details>